### ISSUE TITLE
Plugin is deleting the entire images directory

### ISSUE THREAD

**Issue by djmtype** [kaldor/laravel-mix-clean#13]
When running npm run prod or npm run dev, I see the `public/img` directory get created. However, this plugin destroys the entire `public/img` directory. 

I have a Laravel 8 project. I do need this plugin to remove any stale images found within `public/img`, but not the entire directory.

**Comment by oppiansteve** [comment]
I wouldn't recommend using this plugin then.
This plugin is intended for doing a clean build in isolation from any system.

We're using it to build artefacts which are then written to S3 and are then deployed from S3 to the running system.  i.e. the build and deployment are separate and the clean only cleans the intermediate build artefacts directory.
And for local development where the whole directory is just for a single component's artefacts and nothing else.  (mostly for Wordpress plugins, tbh).

If by stale, you mean ones with old hashes which are no longer tracked then that's potentially a hard problem to solve but perhaps you could implement something that uses the existing mix manifest file in the destination to delete files before deleting the mix file itself.

I suppose that's a more targetted cleaning, but for what we need, we want all files no matter where they came from to be deleted - so we ensure that there's no errant files confusing things.

**Comment by djmtype** [comment]
@oppiansteve It's just kind of odd. The js and css directories are being cleaned yet they aren't being removed like img directory. Also, the img, js and css directories all live at the same level. 

I'll check out the clean webpack plugin to see what's going on there.

**Comment by djmtype** [comment]
I'm using a 3rd-party webpack plugin to generate responsive image sizes. 
https://www.npmjs.com/package/laravel-mix-image-resizer 
This process must be running before the webpack clean plugin. So, your plugin isn't at fault.

**Comment by oppiansteve** [comment]
ah, ok - thanks for updating the ticket
